name: Build

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 1 * *"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the code
        uses: dtolnay/rust-toolchain@stable
      - name: Check that code can compile
        run: cargo build --release
      - name: upload release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/pr-approve
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: v1.0.0
          release_name: v1.0.0
          draft: false
          prerelease: false
