# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the code
        uses: dtolnay/rust-toolchain@stable
      - name: Check that code can compile
        run: cargo build   # Run the `cargo check` command
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}