# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build open-ssl
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev openssl
          which openssl
          openssl version
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
          TOOLCHAIN_VERSION: 1.78
          OPENSSL_DIR: "/usr/local/ssl"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}