name: Build

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 1 * *"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build the code
        uses: dtolnay/rust-toolchain@stable
      - name: Check that code can compile
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-approve
          path: |
            ./target/release/pr-approve
          overwrite: true
          compression-level: 0
          retention-days: 2
